% The main code of generating a wav out of Geomagnetic data
%% Use .mat files generated by readMagDataIAGA2002_KX.m
load('./Chichijima/1min-WWW_mdplt00028978.mat');

%% Raw data processing and normalization
HB=min(dataHori);
VB=min(dataVert);
Hori=dataHori-HB;
Vert=dataVert-VB;
peakW=max(max(Hori),max(Vert));
coefW=5/peakW;

%% generate a syllable for every data point
L=length(dataHori);
H=9600;
keyW=zeros(L,H);
x=1/H:1/H:1;
for i=1:14400
    keyW(i,:)=0.2*exp(-10*x).*(sin(55*power(2,(5-Hori(i)*coefW))*x)+sin(55*power(2,(5-Vert(i)*coefW))*x));
end

%% Add up all the syllables, generate a melody
T=(L-1)*200+H;
melodyW=zeros(T,1);
for i=1:14400
    melodyW(200*(i-1)+1:200*(i-1)+9600)=melodyW(200*(i-1)+1:200*(i-1)+9600)+keyW(i,:)';
end
melodyW=melodyW-mean(melodyW);

%% Output
audiowrite('./Chichijima.wav',melodyW,48000);

